name: Build and Upload intnan to PyPI
on:
  release:
    types:
      - published
  push:
    tags:
      - 'v*'

jobs:
  build-artifacts:
    runs-on: ubuntu-latest
    if: github.repository == 'ml31415/intnan'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: "3.12"

      - name: Build tarball and wheels
        run: |
          git clean -xdf
          git restore -SW .
          uv build
      - name: Check built artifacts
        run: |
          uvx twine check --strict dist/*
          if [ -f dist/intnan-0.0.0.tar.gz ]; then
            echo "❌ INVALID VERSION NUMBER"
            exit 1
          else
            echo "✅ Looks good"
          fi
      - uses: actions/upload-artifact@v4
        with:
          name: releases
          path: dist

  test-built-dist:
    needs: build-artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: "3.12"
      - uses: actions/download-artifact@v4
        with:
          name: releases
          path: dist
      - name: List contents of built dist
        run: |
          ls -ltrh
          ls -ltrh dist
      - name: Verify the built dist/wheel is valid
        if: github.event_name == 'push'
        run: |
          uv venv
          uv pip install dist/intnan*.tar.gz
      - name: Publish package to TestPyPI
        if: github.event_name == 'push'
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.TESTPYPI_TOKEN }}
          repository-url: https://test.pypi.org/legacy/
          verbose: true


  upload-to-pypi:
    needs: test-built-dist
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: releases
          path: dist
      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
          verbose: true
